services:
    php-fpm-exporter:
        image: hipages/php-fpm_exporter:latest
        user: "${WWW_DATA_USER:-33}"
        volumes:
            - ${PHP_FPM_STATUS_SOCKET:-/var/run/php/php-fpm-status.sock}:/tmp/php-fpm.sock
        environment:
            PHP_FPM_SCRAPE_URI: 'unix:///tmp/php-fpm.sock;${PHP_FPM_STATUS_ENDPOINT:-/status}'
        networks:
            - observability
        restart: unless-stopped
    otelcol:
        image: otel/opentelemetry-collector-contrib:latest
        environment:
            - APACHE_STATUS_PORT=${APACHE_STATUS_PORT:-8080}
            - APACHE_STATUS_URL=${APACHE_STATUS_URL:-server-status?auto}
            - MYSQL_PORT=${MYSQL_PORT:-3306}
            - MYSQL_USER=${MYSQL_USER:?MySQL credentials missing}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MySQL credentials missing}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - REDIS_USER=${REDIS_USER:-}
            - REDIS_PASSWORD=${REDIS_PASSWORD:-}
            - HISTOGRAM_MAX_BUCKETS=${HISTOGRAM_MAX_BUCKETS:-320}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./config/otelcol.yml:/etc/otelcol-contrib/config.yaml:ro
            - ${APACHE_ACCESS_LOG:-/var/log/apache2/access.log}:/var/log/apache2/access.log:ro
        group_add:
            - "${DOCKER_CONFIG_GID:?Config GID missing}"
            - "${ADM_GID:-4}" # Add adm group for reading the Apache logs
        networks:
            - default
            - observability
        restart: unless-stopped
    prometheus:
        image: prom/prometheus:latest
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-remote-write-receiver'
            - '--storage.tsdb.retention.time=${PROMETHEUS_TSDB_RETENTION:-1d}'
        volumes:
            - prometheus_data:/prometheus
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        group_add:
            - "${DOCKER_CONFIG_GID:?Config GID missing}"
        networks:
            - observability
        depends_on:
            - otelcol
            - node-exporter
            - php-fpm-exporter
        restart: unless-stopped
    prometheus-proxy:
        image: custom/prom-proxy
        build: ./config/nginx
        pull_policy: never
        ports:
            - "9090:80" # Prometheus UI
        environment:
            - PROM_USERNAME=${PROMETHEUS_USERNAME:?Prometheus credentials missing}
            - PROM_PASSWORD=${PROMETHEUS_PASSWORD:?Prometheus credentials missing}
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/generate-auth.sh:/docker-entrypoint.d/generate-auth.sh:ro
        group_add:
            - "${DOCKER_CONFIG_GID:?Config GID missing}"
        networks:
            - default
            - observability
        depends_on:
            - prometheus
        restart: unless-stopped
    node-exporter:
        image: prom/node-exporter:latest
        command:
            - '--path.rootfs=/host'
            - '--collector.disable-defaults' 
            - '--collector.cpu'
            - '--collector.diskstats'
            - '--collector.filesystem'
            - '--collector.meminfo'
            - '--collector.netstat'
            - '--collector.netdev'
        pid: host
        read_only: true
        networks:
            - observability
        volumes:
            - /:/host:ro
        restart: unless-stopped
    process-exporter:
        image: ncabatoff/process-exporter:latest
        command:
            - -threads=false
            - -config.path=/etc/process-exporter/config.yml
            - --procfs=/host/proc
        cap_add:
            - SYS_PTRACE # Required for PSS memory metrics
        security_opt:
            - apparmor=unconfined
        volumes:
            - /proc:/host/proc:ro
            - ./config/process-exporter.yml:/etc/process-exporter/config.yml:ro
        group_add:
            - "${DOCKER_CONFIG_GID:?Config GID missing}"
        networks:
            - observability
        depends_on:
            - php-fpm-exporter
            - otelcol
            - prometheus
            - prometheus-proxy
            - node-exporter
            - grafana
        restart: unless-stopped
    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000' # Grafana dashboard
        environment:
            - GF_SERVER_HTTP_ADDR=0.0.0.0
            - GF_APP_MODE=production
            - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
            - GF_ANALYTICS_REPORTING_ENABLED=false
            - GF_METRICS_ENABLED=false
        volumes:
            - grafana-data:/var/lib/grafana
            - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
            - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
        group_add:
            - "${DOCKER_CONFIG_GID:?Config GID missing}"
        networks:
            - default
            - observability
        depends_on:
            - prometheus
        restart: unless-stopped
networks:
    observability:
        internal: true
volumes:
    grafana-data:
        driver: local
    prometheus_data:
        driver: local