[www]

; Handle FastCGI requests over TCP
listen = 9000

pm = ondemand
pm.max_children = 2

; Opens a status page for metrics and creates a separate pool and socket to avoid queues
pm.status_path = /status
pm.status_listen = 9001