{
 "title": "App Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mountpoint", "label": "Filesystem", "query": "/" },
   { "name": "drives", "label": "Drive(s)", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU Percentage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - max_over_time(node_memory_MemAvailable_bytes[$__interval])",
     "legendFormat": "Memory Usage"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total Memory" }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\r\n  (rate(node_disk_read_time_seconds_total{device=~\"$drives\"}[$__rate_interval]) + rate(node_disk_write_time_seconds_total{device=~\"$drives\"}[$__rate_interval])) \r\n  / \r\n  (rate(node_disk_reads_completed_total{device=~\"$drives\"}[$__rate_interval]) + rate(node_disk_writes_completed_total{device=~\"$drives\"}[$__rate_interval]))\r\n)",
     "legendFormat": "Disk Latency"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"$mountpoint\"} - node_filesystem_avail_bytes{mountpoint=\"$mountpoint\"}",
     "legendFormat": "Space Used"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"$mountpoint\"}",
     "legendFormat": "Total Space"
    }
   ]
  },
  {
   "title": "Process Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (absent_over_time(apache_uptime_seconds_total[1m]) or vector(0))",
     "legendFormat": "Apache"
    },
    { "expr": "phpfpm_up", "legendFormat": "PHP-FPM" },
    {
     "expr": "1 - (absent_over_time(mysql_uptime_seconds_total[1m]) or vector(0))",
     "legendFormat": "MySQL"
    },
    {
     "expr": "1 - (absent_over_time(redis_uptime_seconds_total[1m]) or vector(0))",
     "legendFormat": "Redis"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "round(histogram_quantile(1.0, rate(apache_latency_milliseconds[$__interval])))",
     "legendFormat": "p100"
    },
    {
     "expr": "round(histogram_quantile(0.99, rate(apache_latency_milliseconds[$__interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "round(histogram_quantile(0.5, rate(apache_latency_milliseconds[$__interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Process Status History",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "min_over_time((1 - (absent_over_time(apache_uptime_seconds_total[1m]) or vector(0)))[$__interval:15s])",
     "legendFormat": "Apache"
    },
    {
     "expr": "min_over_time(phpfpm_up[$__rate_interval])",
     "legendFormat": "PHP-FPM"
    },
    {
     "expr": "min_over_time((1 - (absent_over_time(mysql_uptime_seconds_total[1m]) or vector(0)))[$__interval:15s])",
     "legendFormat": "MySQL"
    },
    {
     "expr": "min_over_time((1 - (absent_over_time(redis_uptime_seconds_total[1m]) or vector(0)))[$__interval:15s])",
     "legendFormat": "Redis"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(apache_status_codes_total[$__interval]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Successful Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(ceil(histogram_count(irate(apache_latency_milliseconds[1m])))[$__interval:15s])",
     "legendFormat": "Requests per second"
    }
   ]
  },
  { "title": "Detailed Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "PHP-FPM Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max_over_time(phpfpm_active_processes[$__interval])",
     "legendFormat": "Active Workers"
    }
   ]
  },
  {
   "title": "Apache Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "max_over_time(apache_workers{state=\"busy\"}[$__interval])",
     "legendFormat": "Busy Workers"
    }
   ]
  },
  {
   "title": "TCP Request Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(node_netstat_TcpExt_ListenDrops[$__interval]))",
     "legendFormat": "TCP Request Drops"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$drives\"}[$__rate_interval]))",
     "legendFormat": "Disk Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$drives\"}[$__rate_interval]))",
     "legendFormat": "Disk Writes"
    }
   ]
  },
  { "title": "Process Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (groupname) (rate(namedprocess_namegroup_cpu_seconds_total[$__rate_interval])) / scalar(count(node_cpu_seconds_total{mode=\"idle\"}))) * 100",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(namedprocess_namegroup_memory_bytes{memtype=\"proportionalResident\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total[$__interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total[$__interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Prometheus Targets",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "min_over_time(up[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "Series" }
   ]
  },
  {
   "title": "Prometheus TSDB Storage Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "TSDB Size"
    }
   ]
  }
 ]
}