receivers:
  apache:
    endpoint: "http://host.docker.internal:${APACHE_STATUS_PORT}/${APACHE_STATUS_URL}"
    collection_interval: 15s
  mysql:
    endpoint: host.docker.internal:${MYSQL_PORT}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    collection_interval: 15s
  redis:
    endpoint: host.docker.internal:${REDIS_PORT}
    username: ${REDIS_USER}
    password: ${REDIS_PASSWORD}
    collection_interval: 15s
  filelog:
    include: ["/var/log/apache2/access.log"]
    operators:
      - type: regex_parser
        regex: '^(?P<host>[^ ]+) (?P<ident>[^ ]+) (?P<user>[^ ]+) \[(?P<timestamp>.+)\] "(?P<request>.+)" (?P<status>\d+) (?P<size>[^ ]+) (?P<latency_us>\d+) "(?P<referer>.*?)" "(?P<agent>.*?)"$'

processors:
  batch:
  deltatocumulative:
    max_stale: 30m

connectors:
  signaltometrics:
    logs:
      - name: apache_status_codes_total
        description: Occurrences of Apache status codes
        sum:
          value: "1"
        attributes:
          - key: status
      - name: apache_latency_milliseconds
        description: Apache request latency as exponential histogram
        conditions:
          # Only store successful requests
          # Most POST requests in my apps respond with a redirect, so include both 2xx and 3xx responses
          - IsMatch(attributes["status"], "^[23].*")
        exponential_histogram:
          # Convert to milliseconds and store
          value: Int(Int(attributes["latency_us"]) / 1000)
          max_size: ${HISTOGRAM_MAX_BUCKETS}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    
    # Metrics that have not received data will be removed from memory and will no longer be available for scraping
    # Default is 5m
    metric_expiration: 30m
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [signaltometrics]
    metrics:
      receivers: [signaltometrics]
      processors: [deltatocumulative, batch]
      exporters: [prometheus]
    metrics/apache-status:
      receivers: [apache]
      processors: []
      exporters: [prometheusremotewrite]
    metrics/mysql:
      receivers: [mysql]
      processors: []
      exporters: [prometheusremotewrite]
    metrics/redis:
      receivers: [redis]
      processors: []
      exporters: [prometheusremotewrite]
  telemetry:
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888