process_names:
  - comm:
    - apache2
    - mariadbd
    - redis-server
    - grafana
    - prometheus
    - node_exporter
    - otelcol-contrib
  - name: "prom-proxy"
    comm:
      - "nginx"
  - name: "php-fpm"
    comm:
      - "php-fpm8.5"
    cmdline:
      - "php-fpm: pool"
  - name: "php-fpm-exporter"
    cmdline:
      - php-fpm_exporter
  - name: "process-exporter"
    cmdline:
      - process-exporter