Listen 8080

# Maximum length of the queue of pending connections
# Reduced from the default of 511 to prevent long queues in front of Apache, which would not be measured in the recorded latency
ListenBackLog 16