[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/apache.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3