[program:atop]
; -w: path to the log file (we use a daily log format)
; -a: capture all processes (even those that exited)
; 60: the interval in seconds
command=/usr/bin/atop -w /var/log/atop/atop_current -a 60
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/log/atop.out.log