[program:node_exporter]
command=/usr/local/bin/node_exporter --collector.disable-defaults --collector.cpu --collector.diskstats --collector.filesystem --collector.meminfo --collector.netstat

user=root
autostart=true
autorestart=true
startsecs=5
startretries=3

redirect_stderr=true
stdout_logfile=/var/log/node_exporter.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3