[program:process-exporter]
command=/usr/local/bin/process-exporter -threads=false -config.path /etc/process-exporter/config.yml

user=root
autostart=true
autorestart=true
startsecs=5
startretries=3

redirect_stderr=true
stdout_logfile=/var/log/process-exporter.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3