[program:prometheus]
command=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --storage.tsdb.retention.time=1d
user=root
autostart=true
autorestart=true
startsecs=5
stopsignal=INT
redirect_stderr=true
stdout_logfile=/var/log/prometheus.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
